// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKn8-ZEMUOMRRvicYod5immKRxXxsn_sQ',
    appId: '1:500130961602:web:46aaa36557c6a8ad38c35b',
    messagingSenderId: '500130961602',
    projectId: 'mycontacts-602c6',
    authDomain: 'mycontacts-602c6.firebaseapp.com',
    storageBucket: 'mycontacts-602c6.appspot.com',
    measurementId: 'G-L2J3LRVTLW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRW2T7UUCsM0y664wLe8-CSFxNd8KcWm0',
    appId: '1:500130961602:android:06990270b917ca5938c35b',
    messagingSenderId: '500130961602',
    projectId: 'mycontacts-602c6',
    storageBucket: 'mycontacts-602c6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkFj5ibzmWF13EschH1-POnOcmeYrNwN4',
    appId: '1:500130961602:ios:ff281c57d010532138c35b',
    messagingSenderId: '500130961602',
    projectId: 'mycontacts-602c6',
    storageBucket: 'mycontacts-602c6.appspot.com',
    iosBundleId: 'com.example.myContacts',
  );
}
